import { Religion, Post, User, Member, Mission } from "@/types";

export const mockUser: User = {
  id: "user-b",
  displayName: "信者B",
  email: "user@example.com",
  avatarIcon: "💫",
  coins: 1250,
  level: 12,
  xp: 450,
  xpToNext: 750,
  foundedReligionIds: [],
  joinedReligionIds: ["religion-1", "religion-2", "religion-3"],
  createdAt: new Date(),
};

export const mockReligions: Religion[] = [
  {
    id: "religion-1",
    name: "朝ごはんはパン教",
    icon: "🍞",
    doctrine:
      "朝の食事はパンであるべし。焼きたてのパンの香りは心を豊かにし、バターの滑らかさは魂を癒す。我々はパンと共に目覚め、パンと共に一日を始める。米も良いが、パンこそが至高である。クロワッサン、食パン、バゲット、すべてのパンに感謝を。",
    category: "食文化",
    isPublic: true,
    founderUserId: "user-000",
    founderName: "教祖000",
    memberCount: 12543,
    level: 25,
    scriptureCount: 5,
    hymnCount: 3,
    totalOfferings: 85000,
    weeklyGrowth: 234,
    pinnedMessage: "次回の大集会は日曜日10:00です。全員参加をお願いします。🍞",
    createdAt: new Date(),
  },
  {
    id: "religion-2",
    name: "コーヒーは至高教",
    icon: "☕",
    doctrine:
      "湯温は92度。円を描くように、ゆっくりと注ぐのだ。コーヒーとは忍耐であり、待者にのみ至高の一杯が訪れる。",
    category: "食文化",
    isPublic: true,
    founderUserId: "user-caffeine",
    founderName: "カフェイン大師",
    memberCount: 58201,
    level: 42,
    scriptureCount: 8,
    hymnCount: 5,
    totalOfferings: 420000,
    weeklyGrowth: 1205,
    createdAt: new Date(),
  },
  {
    id: "religion-3",
    name: "昼寝は正義教",
    icon: "😮",
    doctrine:
      "昼食後の眠気は自然の摂理である。我々は午後の一時、静かに目を閉じ、心身を休める。15分の仮眠は3時間の修行に匹敵する。眠れ、そして目覚めよ。",
    category: "ライフスタイル",
    isPublic: true,
    founderUserId: "user-sleeper",
    founderName: "眠りの賢者",
    memberCount: 32104,
    level: 35,
    scriptureCount: 3,
    hymnCount: 2,
    totalOfferings: 165000,
    weeklyGrowth: 567,
    createdAt: new Date(),
  },
  {
    id: "religion-4",
    name: "猫こそ神教",
    icon: "🐱",
    doctrine: "猫は神である。その優雅な動き、気まぐれな性格、すべては完璧だ。",
    category: "趣味・エンタメ",
    isPublic: true,
    founderUserId: "user-cat",
    founderName: "にゃんこ教主",
    memberCount: 45892,
    level: 38,
    scriptureCount: 6,
    hymnCount: 4,
    totalOfferings: 310000,
    weeklyGrowth: 890,
    createdAt: new Date(),
  },
  {
    id: "religion-5",
    name: "ゲームは文化教",
    icon: "🎮",
    doctrine:
      "ゲームは単なる娯楽にあらず。それは文化であり、芸術であり、コミュニケーションである。",
    category: "趣味・エンタメ",
    isPublic: true,
    founderUserId: "user-gamer",
    founderName: "ゲーム仙人",
    memberCount: 9876,
    level: 22,
    scriptureCount: 4,
    hymnCount: 2,
    totalOfferings: 78000,
    weeklyGrowth: 234,
    createdAt: new Date(),
  },
  {
    id: "religion-6",
    name: "毎朝ランニング教",
    icon: "🏃",
    doctrine:
      "夜明けと共に走れ。汗は魂の浄化であり、毎朝5kmが悟りへの道である。",
    category: "スポーツ",
    isPublic: true,
    founderUserId: "user-runner",
    founderName: "マラソン聖人",
    memberCount: 7654,
    level: 20,
    scriptureCount: 3,
    hymnCount: 1,
    totalOfferings: 56000,
    weeklyGrowth: 178,
    createdAt: new Date(),
  },
  {
    id: "religion-7",
    name: "ラーメンは命教",
    icon: "🍜",
    doctrine:
      "ラーメンは単なる食事にあらず。それは魂の糧であり、スープの一滴に宇宙が宿る。",
    category: "食文化",
    isPublic: true,
    founderUserId: "user-ramen",
    founderName: "麺の導師",
    memberCount: 6321,
    level: 19,
    scriptureCount: 4,
    hymnCount: 2,
    totalOfferings: 45000,
    weeklyGrowth: 145,
    createdAt: new Date(),
  },
  {
    id: "religion-8",
    name: "観葉植物教",
    icon: "🌿",
    doctrine:
      "緑は癒しである。植物と共に暮らすことで、人は自然と一体になれる。",
    category: "自然・環境",
    isPublic: true,
    founderUserId: "user-plant",
    founderName: "緑の使徒",
    memberCount: 4567,
    level: 15,
    scriptureCount: 2,
    hymnCount: 1,
    totalOfferings: 28000,
    weeklyGrowth: 98,
    createdAt: new Date(),
  },
  {
    id: "religion-9",
    name: "読書は救い教",
    icon: "📚",
    doctrine: "一日一冊、魂に栄養を。知識は光であり、無知は闇である。",
    category: "学問・教養",
    isPublic: true,
    founderUserId: "user-book",
    founderName: "書物の聖者",
    memberCount: 3210,
    level: 14,
    scriptureCount: 7,
    hymnCount: 3,
    totalOfferings: 22000,
    weeklyGrowth: 87,
    createdAt: new Date(),
  },
  {
    id: "religion-10",
    name: "推し活は宗教教",
    icon: "🌟",
    doctrine:
      "推しへの愛は信仰である。グッズを買い、現場に行き、愛を叫べ。それが救済への道だ。",
    category: "趣味・エンタメ",
    isPublic: true,
    founderUserId: "user-oshi",
    founderName: "オタクの聖人",
    memberCount: 2340,
    level: 12,
    scriptureCount: 3,
    hymnCount: 5,
    totalOfferings: 180000,
    weeklyGrowth: 2340,
    createdAt: new Date(),
  },
];

export const mockPosts: Post[] = [
  {
    id: "post-1",
    religionId: "religion-1",
    religionName: "朝ごはんはパン教",
    religionIcon: "🍞",
    authorId: "user-000",
    authorName: "教祖000",
    authorIcon: "😊",
    authorRole: "教祖",
    type: "啓示",
    content:
      '本日の啓示：「焼きたてのパンには何もつけずにまず一口。小麦の恵みを感じるのです。」\n\n皆さん、今朝のパンはいかがでしたか？写真を共有してください🍞✨',
    prayerCount: 432,
    replyCount: 89,
    missionaryCount: 56,
    hasPrayed: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "post-2",
    religionId: "religion-2",
    religionName: "コーヒーは至高教",
    religionIcon: "☕",
    authorId: "user-caffeine",
    authorName: "カフェイン大師",
    authorIcon: "🐼",
    authorRole: "教祖",
    type: "経典",
    content:
      '新経典「ドリップの書 第三章」を公開しました。\n\n「湯温は92度。円を描くように、ゆっくりと注ぐのだ。コーヒーとは忍耐であり、待者にのみ至高の一杯が訪れる。」',
    scriptureTitle: "ドリップの書 第三章",
    prayerCount: 1204,
    replyCount: 234,
    missionaryCount: 189,
    hasPrayed: true,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: "post-3",
    religionId: "religion-1",
    religionName: "朝ごはんはパン教",
    religionIcon: "🍞",
    authorId: "user-b",
    authorName: "信者B",
    authorIcon: "💫",
    authorRole: "信者",
    type: "ミッション達成",
    content:
      "ミッション「パンの写真を投稿」を達成しました！\n\n今朝はベーカリーで買ったメロンパンです。外はサクサク、中はふわふわ。パンの教えを体現した至高の一品でした。🙏",
    prayerCount: 67,
    replyCount: 12,
    missionaryCount: 8,
    coinsEarned: 100,
    hasPrayed: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "post-4",
    religionId: "religion-3",
    religionName: "昼寝は正義教",
    religionIcon: "😮",
    authorId: "user-sleeper",
    authorName: "眠りの賢者",
    authorIcon: "💤",
    authorRole: "教祖",
    type: "啓示",
    content:
      "今日のお告げ：「昼食後の15分は神聖な時間である。誰も邪魔をしてはならない。」\n\n皆さん、今日も聖なる昼寝を達成できましたか？😴",
    prayerCount: 892,
    replyCount: 156,
    missionaryCount: 78,
    hasPrayed: false,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: "post-5",
    religionId: "religion-4",
    religionName: "猫こそ神教",
    religionIcon: "🐱",
    authorId: "user-cat",
    authorName: "にゃんこ教主",
    authorIcon: "🐈",
    authorRole: "教祖",
    type: "お知らせ",
    content:
      "本日、信者数45,000人突破！皆様のご支援に感謝します。\n\n神々しき猫様の写真投稿キャンペーンを開始します。最優秀作品には特別コイン1000枚を授与します🏆",
    prayerCount: 2341,
    replyCount: 445,
    missionaryCount: 312,
    hasPrayed: true,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
];

export const mockMembers: Member[] = [
  { userId: "user-000", displayName: "教祖000", avatarIcon: "😊", role: "教祖", level: 25 },
  { userId: "user-a", displayName: "信者A", avatarIcon: "🔥", role: "副教祖", level: 18 },
  { userId: "user-b", displayName: "信者B", avatarIcon: "💫", role: "信者", level: 12 },
];

export const mockMissions: Mission[] = [
  { id: "m1", religionId: "religion-1", title: "朝食にパンを食べる", reward: 50, completed: false },
  { id: "m2", religionId: "religion-1", title: "パンの写真を投稿", reward: 100, completed: true },
  { id: "m3", religionId: "religion-1", title: "集会に3回発言する", reward: 75, completed: false },
];

export const mockChatMessages = [
  {
    id: "msg-1",
    religionId: "religion-1",
    authorId: "user-000",
    authorName: "教祖000",
    authorIcon: "😊",
    authorRole: "教祖" as const,
    content: "皆さん、おはようございます。今朝はクロワッサンを焼きました。バターの香りが最高です！🥐",
    createdAt: new Date(Date.now() - 50 * 60 * 1000),
  },
  {
    id: "msg-2",
    religionId: "religion-1",
    authorId: "user-a",
    authorName: "信者A",
    authorIcon: "🔥",
    authorRole: "副教祖" as const,
    content: "教祖様、おはようございます！私は今朝フランスパンをいただきました。パンの教えに従い、良い一日のスタートです。",
    createdAt: new Date(Date.now() - 48 * 60 * 1000),
  },
  {
    id: "msg-3",
    religionId: "religion-1",
    authorId: "user-b",
    authorName: "信者B",
    authorIcon: "💫",
    authorRole: "信者" as const,
    content: "おはようございます！今日のミッション「朝食にパンを食べる」達成しました！🍞✨",
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
  },
  {
    id: "msg-4",
    religionId: "religion-1",
    authorId: "user-000",
    authorName: "教祖000",
    authorIcon: "😊",
    authorRole: "教祖" as const,
    content: "素晴らしい！パンの恵みがあなたに訪れるでしょう。50コインを授けます。🙏",
    createdAt: new Date(Date.now() - 43 * 60 * 1000),
  },
  {
    id: "msg-5",
    religionId: "religion-1",
    authorId: "user-c",
    authorName: "信者C",
    authorIcon: "🌸",
    authorRole: "信者" as const,
    content: "今朝はメープルシロップをかけたパンケーキにしました。これもパンの一種ですよね？🥞",
    createdAt: new Date(Date.now() - 40 * 60 * 1000),
  },
];
